[project]
name = "proyecto-api-base-datos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.118.0",
    "sqlalchemy>=2.0.43",
]
